{
  "cpu": 512,
  "environment": [],
  "environmentFiles": [],
  "essential": true,
  "image": "040291911741.dkr.ecr.us-east-1.amazonaws.com/student-performance:latest",
  "logConfiguration": {
    "logDriver": "awslogs",
    "options": {
      "awslogs-group": "/ecs/",
      "awslogs-create-group": "true",
      "awslogs-region": "us-east-1",
      "awslogs-stream-prefix": "ecs"
    },
    "secretOptions": []
  },
  "memory": 1024,
  "memoryReservation": 1024,
  "mountPoints": [],
  "name": "student-performance-container",
  "portMappings": [
    {
      "appProtocol": "http",
      "containerPort": 5000,
      "hostPort": 5000,
      "name": "student-performance-container-5000-tcp",
      "protocol": "tcp"
    }
  ],
  "systemControls": [],
  "ulimits": [],
  "volumesFrom": []
}
